M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Wed 13 Mar 2024 22:54:39 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-13T22:54:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X133.234Y-74.9
X133.234Y-89.6
X165.234Y-74.9
X165.234Y-89.6
T0
M30
