M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Fri 15 Mar 2024 11:13:56 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-15T11:13:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X63.436Y-65.605
X69.216Y-65.605
T2
X80.899Y-61.467
T0
M30
